clear
close
clc
%% Autonomous Learning Multi-Model System for Binary Classification
load classificationexample
input.X=tradata;
input.Y=tralabel;
% input.X are the inputs of the system
% input.Y are the corresponding labels of the inputs
[output]=FirstOrderALMMoSystem(input,'OnlineLearning','Classification'); %% Online classification;
% output.TrainedSystem is the trained ALMMo-1 system
% output.Estimation are the estimated label generated by the ALMMo-1 system with the respective inputs in an online manner.
%%  Validation after Online Training; System Stop Updating
input.TrainedSystem=output.TrainedSystem;
input.X=tesdata;
% input.X are the inputs of the system
% input.TrainedSystem is the pretrained ALMMo-1 system
[output]=FirstOrderALMMoSystem(input,'Validation','Classification'); %% System validation;
% output are the estimated labels generated by the ALMMo-1 system with the respective inputs
confusionmatrix=confusionmat(teslabel,output) % confusion matrix