clear
close
clc
%% Autonomous Learning Multi-Model System for Regression
%% Online Training for Regression
load regressionexample
input.X=data;
input.Y=Y;
% input.X are the inputs of the system
% input.Y are the targeted outputs of the system
[output]=FirstOrderALMMoSystem(input,'OnlineLearning','Regression'); %% Online regression;
% output.TrainedSystem are the trained ALMMo-1 system
% output.Estimation are the outputs generated by the ALMMo-1 system with the respective inputs in an online manner.
CORR=min(min(corrcoef(output.Estimation,Y)))% correlation co-efficient
RMSE=sqrt(mean((output.Estimation-Y).^2)) % Root mean square error (RMSE)
NDEI=RMSE/(std(Y)) % non-dimensional error index (NDEI)
%% Validation after Online Training; System Stop Updating
input.TrainedSystem=output.TrainedSystem;
input.X=data;
% input.X are the inputs of the system
% input.TrainedSystem is the pretrained ALMMo-1 system
[output]=FirstOrderALMMoSystem(input,'Validation','Regression'); %% System validation;
% output are the outputs generated by the ALMMo-1 system with the respective inputs
CORR=min(min(corrcoef(output,Y)))% correlation co-efficient
RMSE=sqrt(mean((output-Y).^2)) % Root mean square error (RMSE)
NDEI=RMSE/(std(Y)) % non-dimensional error index (NDEI)